[project]
name = "flashcards-in-a-flash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "genanki>=0.13.1",
]
